const $ = s => document.querySelector(s);
const app = $('#app');
const modal = $('#modal');
const modalBody = $('#modalBody');
const toast = $('#toast');

const KEY='glmx_v02';
const defaults={
  accounts:[{id:'acc1',name:'主号'}], current:'acc1',
  profiles:{acc1:{agents:[
    {id:'a1',name:'张邈',level:90,stars:3,rank:15,atk:3450,hp:18200,fate:'命盘一 / 命盘二 / 命盘三',stones:'天府·橙·Lv30；攻击辅星·紫·Lv25'},
    {id:'a2',name:'董奉',level:90,stars:2,rank:15,atk:3180,hp:19400,fate:'命盘一 / 命盘二',stones:'生命主星·橙·Lv30'},
    {id:'a3',name:'诸葛亮',level:90,stars:1,rank:15,atk:3310,hp:17600,fate:'命盘一 / 命盘二',stones:'攻击主星·紫·Lv28'},
    {id:'a4',name:'刘璋',level:80,stars:2,rank:14,atk:2880,hp:17100,fate:'命盘一',stones:'未装备'},
    {id:'a5',name:'陈登',level:90,stars:5,rank:15,atk:3050,hp:18150,fate:'命盘一 / 命盘二',stones:'生命辅星·紫·Lv25'},
    {id:'a6',name:'杨修',level:90,stars:4,rank:15,atk:3600,hp:16800,fate:'命盘一 / 命盘二',stones:'攻击主星·橙·Lv30'}
  ], stones:[
    {id:'s1',name:'天府',level:30,count:1,kind:'主星',quality:'橙',bonus:'攻击 +15%',equipped:'张邈'},
    {id:'s2',name:'攻击辅星',level:25,count:2,kind:'辅星',quality:'紫',bonus:'攻击 +8%',equipped:'张邈'}
  ], pools:[
    {id:'p1',name:'绣衣天下',note:'常驻卡池',totalPulls:1095,golds:[
      {name:'张邈',gap:37,status:'UP'},{name:'董奉',gap:64,status:'歪'},{name:'诸葛亮',gap:22,status:'UP'},{name:'杨修',gap:71,status:'保底'}
    ]},
    {id:'p2',name:'雀部限时',note:'限时卡池',totalPulls:210,golds:[{name:'陈登',gap:48,status:'UP'},{name:'张邈',gap:66,status:'歪'}]}
  ]}},
  guides:[
    {id:'g1',title:'兰台 5-30',author:'梨花瓷',type:'常驻',status:'已发布',created:'2026-09-09',lastSuccess:'2天前',successCount:27,match:91,matchLabel:'基本匹配',tags:['低星','无限定','高练度'],team:['张邈','董奉','诸葛亮','刘璋','陈登'],members:[
      {name:'张邈',level:90,stars:3,rank:15,atk:3450,hp:18200,fate:'命盘一 / 命盘二 / 命盘三',stones:'天府·橙·Lv30；攻击辅星·紫·Lv25'},
      {name:'董奉',level:90,stars:2,rank:15,atk:3180,hp:19400,fate:'命盘一 / 命盘二',stones:'生命主星·橙·Lv30'},
      {name:'诸葛亮',level:90,stars:1,rank:15,atk:3310,hp:17600,fate:'命盘一 / 命盘二',stones:'攻击主星·紫·Lv28'},
      {name:'刘璋',level:80,stars:2,rank:14,atk:2880,hp:17100,fate:'命盘一',stones:'未装备'},
      {name:'陈登',level:90,stars:5,rank:15,atk:3050,hp:18150,fate:'命盘一 / 命盘二',stones:'生命辅星·紫·Lv25'}
    ], rounds:[
      {actions:['1A','2↑','3A','4↓','5A'],note:'这里需要赌一次暴击。'},
      {actions:['1↑','2A','3A','4↓','5A'],note:''}
    ],note:'攻击略低一点也可能通过；如果第1回合没有暴击可以重开。',reports:0,attempted:12}
  ]
};

let state=load();
let view={page:'home',guideTab:'all',guideSearch:'',poolId:null};
function load(){try{return JSON.parse(localStorage.getItem(KEY))||structuredClone(defaults)}catch(e){return structuredClone(defaults)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function profile(){return state.profiles[state.current]}
function account(){return state.accounts.find(a=>a.id===state.current)}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function showToast(msg){toast.textContent=msg;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1600)}
function avatar(name,cls=''){return `<div class="avatar ${cls}">${esc((name||'?').slice(0,1))}</div>`}
function setPage(page,extra={}){view={...view,page,...extra};render();window.scrollTo({top:0,behavior:'smooth'})}
function head(title,sub=''){return `<div class="page-head"><div><button class="back" data-page="home">← 首页</button><h2>${title}</h2>${sub?`<p>${sub}</p>`:''}</div></div>`}
function render(){ $('#accountBtn').textContent=(account()?.name||'主号')+' ▾'; const p=view.page; if(p==='home')return renderHome(); if(p==='agents')return renderAgents(); if(p==='guides')return renderGuides(); if(p==='guideDetail')return renderGuideDetail(view.guideId); if(p==='guideCreate')return renderGuideCreate(); if(p==='adapt')return renderGuides(true); if(p==='stones')return renderStones(); if(p==='recruit')return renderRecruit(); if(p==='pool')return renderPool(view.poolId); if(p==='dex')return renderDex(); }

function renderHome(){app.innerHTML=`
<section class="hero card"><h2>从自己的密探出发，找到真正能抄的攻略。</h2><p>记录当前账号的密探与星石，制作攻略时自动导入，也能更快筛出与你配置相近的作业。</p></section>
<div class="home-grid">
${feature('我的密探','等级 · 命盘 · 星石','人','agents')}
${feature('攻略库','搜索 · 发布 · 复现','策','guides')}
${feature('适配攻略','完全匹配 · 基本匹配','合','adapt')}
${feature('星石记录','纯文字 · 装备联动','星','stones')}
${feature('招募记录','卡池 · 第几金 · 几抽','鸢','recruit')}
${feature('密探图鉴','功能暂留空','录','dex',true)}
</div>`; bindNav()}
function feature(t,s,i,p,placeholder=false){return `<button class="feature ${placeholder?'placeholder':''}" data-page="${p}"><div class="ico">${i}</div><b>${t}</b><small>${s}</small></button>`}
function bindNav(){document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>setPage(b.dataset.page))}

function renderAgents(){const q=''; app.innerHTML=head('我的密探','只维护会影响攻略适配的数据。')+`
<div class="toolbar"><input class="search" id="agentSearch" placeholder="搜索密探名"><select id="agentFilter"><option>全部</option><option>已拥有</option></select><button class="primary" id="addAgent">＋ 添加密探</button></div>
<div class="hint">属性与职位由系统密探资料自动带出，不需要玩家填写；可切换属性的特殊密探后续单独处理。</div>
<div class="stack" id="agentList">${profile().agents.map(agentCard).join('')}</div>`;
 bindNav(); $('#agentSearch').oninput=e=>filterAgents(e.target.value); $('#addAgent').onclick=()=>agentModal(); document.querySelectorAll('[data-agent-edit]').forEach(b=>b.onclick=()=>agentModal(b.dataset.agentEdit));}
function agentCard(a){return `<div class="agent-card card" data-agent-name="${esc(a.name)}"><div class="row between"><div class="row">${avatar(a.name)}<div><h3>${esc(a.name)}</h3><div class="meta">Lv.${a.level} · ${a.stars}星 · 修为${a.rank}</div></div></div><button class="soft" data-agent-edit="${a.id}">编辑</button></div><div class="chips"><span class="chip">攻击 ${a.atk}</span><span class="chip">生命 ${a.hp}</span><span class="chip">命盘 ${esc(a.fate||'未录入')}</span><span class="chip">星石 ${esc(a.stones||'未装备')}</span></div></div>`}
function filterAgents(v){document.querySelectorAll('[data-agent-name]').forEach(el=>el.style.display=el.dataset.agentName.includes(v.trim())?'':'none')}
function agentModal(id){const p=profile(); const a=id?p.agents.find(x=>x.id===id):{id:'a'+Date.now(),name:'',level:90,stars:1,rank:15,atk:0,hp:0,fate:'',stones:''}; modalBody.innerHTML=`<div class="modal-head"><h3>${id?'编辑密探':'添加密探'}</h3><button class="close" id="mclose">×</button></div><div class="form-grid">
<label>密探名称<input id="mName" value="${esc(a.name)}"></label><label>等级<input id="mLevel" type="number" value="${a.level}"></label><label>星级<input id="mStars" type="number" min="0" max="5" value="${a.stars}"></label><label>修为<input id="mRank" type="number" value="${a.rank}"></label><label>攻击<input id="mAtk" type="number" value="${a.atk}"></label><label>生命<input id="mHp" type="number" value="${a.hp}"></label><label>命盘<input id="mFate" value="${esc(a.fate)}"></label><label>当前装备星石<input id="mStones" value="${esc(a.stones)}"></label></div><div class="form-actions"><button class="soft" id="mCancel">取消</button><button class="primary" id="mSave">保存</button></div>`; modal.showModal(); $('#mclose').onclick=$('#mCancel').onclick=()=>modal.close(); $('#mSave').onclick=()=>{const obj={...a,name:$('#mName').value.trim(),level:+$('#mLevel').value,stars:+$('#mStars').value,rank:+$('#mRank').value,atk:+$('#mAtk').value,hp:+$('#mHp').value,fate:$('#mFate').value.trim(),stones:$('#mStones').value.trim()}; if(!obj.name)return showToast('请填写密探名称'); if(id)p.agents[p.agents.findIndex(x=>x.id===id)]=obj; else p.agents.push(obj); save();modal.close();renderAgents();showToast('已保存')};}

function renderGuides(adaptOnly=false){let guides=state.guides.slice(); if(adaptOnly)guides=guides.filter(g=>g.match>=50); const q=(view.guideSearch||'').trim(); if(q)guides=guides.filter(g=>[g.title,g.author,...g.team].join(' ').includes(q)); app.innerHTML=head(adaptOnly?'适配攻略':'攻略库',adaptOnly?'根据当前账号筛选攻略。':'搜索关卡、章节或制作人 ID。')+`
<div class="toolbar"><input class="search" id="guideSearch" placeholder="搜索关卡名 / 章节 / 制作人 ID" value="${esc(view.guideSearch||'')}">${adaptOnly?'':`<button class="primary" id="publishGuide">＋ 发布攻略</button>`}</div>
<div class="tabs">${['全部','适配我的','我的收藏','我的攻略'].map((x,i)=>`<button class="tab ${i===0?'active':''}">${x}</button>`).join('')}</div>
<div class="stack">${guides.length?guides.map(guideCard).join(''):`<div class="card empty">暂无符合条件的攻略</div>`}</div>`;
 bindNav(); $('#guideSearch').oninput=e=>{view.guideSearch=e.target.value; renderGuides(adaptOnly)}; if($('#publishGuide'))$('#publishGuide').onclick=()=>setPage('guideCreate'); document.querySelectorAll('[data-guide]').forEach(c=>c.onclick=()=>setPage('guideDetail',{guideId:c.dataset.guide}));}
function guideCard(g){const cls=g.match>=95?'ok':g.match>=60?'warn':'bad'; return `<div class="guide-card card" data-guide="${g.id}"><div class="guide-top"><div><h3>${esc(g.title)}</h3><div class="meta">by ${esc(g.author)}</div></div><span class="match ${cls}">${g.match}% · ${esc(g.matchLabel)}</span></div><div class="avatar-row">${g.team.map(n=>avatar(n,'sm')).join('')}</div><div class="guide-foot"><div>${g.successCount} 人成功复现 · 最近成功 ${esc(g.lastSuccess)}</div><div>${g.status==='待复核'?'<span class="chip bad">⚠ 待作者复核</span>':''}</div></div><div class="chips">${g.tags.slice(0,3).map(t=>`<span class="chip">${esc(t)}</span>`).join('')}</div></div>`}

function renderGuideDetail(id){const g=state.guides.find(x=>x.id===id); if(!g)return setPage('guides'); const cls=g.match>=95?'ok':g.match>=60?'warn':'bad'; app.innerHTML=head('攻略详情')+`
<div class="detail-hero card"><div class="row between"><div><h2>${esc(g.title)}</h2><div class="meta">制作人 ${esc(g.author)} · 发布于 ${g.created}</div></div><span class="match ${cls}">${g.match}% · ${esc(g.matchLabel)}</span></div>
<div class="compare-summary"><strong>与你的「${esc(account().name)}」比较</strong><div class="compare-list">4/5 密探完全满足<br>张邈攻击低 160<br>缺 1 个关键命盘<br>辅星品质低一级</div><button class="soft" id="compareBtn">查看详细对比</button></div></div>
<h3 class="section-title">阵容配置</h3><div class="member-list">${g.members.map(memberCard).join('')}</div>
<h3 class="section-title">回合操作</h3>${g.rounds.map((r,i)=>`<div class="round card"><b>第 ${i+1} 回合</b><div class="chips">${g.team.map((n,j)=>`<span class="chip">${esc(n)} · ${esc(r.actions[j]||'')}</span>`).join('')}</div>${r.note?`<div class="note" style="margin-top:8px">${esc(r.note)}</div>`:''}</div>`).join('')}
<h3 class="section-title">作者备注</h3><div class="note">${esc(g.note||'暂无')}</div>
<div class="card" style="padding:14px;margin-top:12px"><div class="row between"><div><b>${g.successCount} 人成功复现</b><div class="meta">最近成功 ${esc(g.lastSuccess)}</div></div><div class="row"><button class="soft" id="reportBtn">反馈问题</button><button class="primary" id="successBtn">✓ 我用这个攻略通过了</button></div></div></div>`;
 bindNav(); $('#successBtn').onclick=()=>{g.successCount++;g.lastSuccess='刚刚';save();renderGuideDetail(id);showToast('已记录成功复现')}; $('#reportBtn').onclick=()=>reportModal(g); $('#compareBtn').onclick=()=>compareModal(g);}
function memberCard(m){return `<div class="member"><div class="row">${avatar(m.name,'sm')}<div><b>${esc(m.name)}</b><div class="meta">Lv.${m.level} · ${m.stars}星 · 修为${m.rank}</div></div></div><div class="mini-grid"><div>攻击<b>${m.atk}</b></div><div>生命<b>${m.hp}</b></div><div>命盘<b>${esc(m.fate)}</b></div><div>星石<b>${esc(m.stones)}</b></div></div></div>`}
function reportModal(g){modalBody.innerHTML=`<div class="modal-head"><h3>反馈问题</h3><button class="close" id="mclose">×</button></div><label>问题类型<select id="reportType"><option>阵容信息错误</option><option>命盘错误</option><option>星石错误</option><option>回合操作错误</option><option>面板信息错误</option><option>已无法复现</option><option>其他</option></select></label><label style="margin-top:10px">补充说明<textarea id="reportText" placeholder="一句话说明哪里可能有问题"></textarea></label><div class="form-actions"><button class="soft" id="mCancel">取消</button><button class="primary" id="mSave">提交反馈</button></div>`;modal.showModal();$('#mclose').onclick=$('#mCancel').onclick=()=>modal.close();$('#mSave').onclick=()=>{g.reports=(g.reports||0)+1;g.attempted=(g.attempted||0)+1;if(g.attempted>=5&&g.reports>=3&&g.reports/g.attempted>=.4)g.status='待复核';save();modal.close();renderGuideDetail(g.id);showToast('反馈已提交')};}
function compareModal(g){const mine=profile().agents; modalBody.innerHTML=`<div class="modal-head"><h3>与你当前账号比较</h3><button class="close" id="mclose">×</button></div>${g.members.map(m=>{const x=mine.find(a=>a.name===m.name);return `<div class="member" style="margin-bottom:8px"><b>${esc(m.name)}</b><div class="mini-grid"><div>作者攻击<b>${m.atk}</b></div><div>我的攻击<b>${x?x.atk:'未拥有'}</b></div><div>作者生命<b>${m.hp}</b></div><div>我的生命<b>${x?x.hp:'未拥有'}</b></div><div>作者命盘<b>${esc(m.fate)}</b></div><div>我的命盘<b>${esc(x?.fate||'—')}</b></div><div>作者星石<b>${esc(m.stones)}</b></div><div>我的星石<b>${esc(x?.stones||'—')}</b></div></div></div>`}).join('')}`;modal.showModal();$('#mclose').onclick=()=>modal.close();}

function renderGuideCreate(){const agents=profile().agents; app.innerHTML=head('发布攻略','从当前账号自动导入，导入后仍可单独修改本篇配置。')+`
<div class="form-card card"><div class="form-grid"><label>关卡名称<input id="gcTitle" placeholder="例如：兰台 5-30"></label><label>关卡类型<select id="gcType"><option>常驻</option><option>限时</option></select></label><label id="endWrap" style="display:none">活动结束日期<input type="date" id="gcEnd"></label><label>制作人 ID<input id="gcAuthor" value="${esc(account().name)}"></label></div><div id="limitHint" class="hint" style="display:none;margin-top:10px">这是限时关卡攻略。活动结束后将进入归档，并在 30 天后自动删除。请提前导出备份。</div></div>
<h3 class="section-title">选择 5 个密探</h3><div class="agent-select" id="agentSelect">${agents.map(a=>`<button class="select-tile" data-pick="${a.id}">${avatar(a.name,'sm')}<b>${esc(a.name)}</b></button>`).join('')}</div>
<div id="pickedEditors"></div>
<h3 class="section-title">回合操作</h3><div class="hint">A = 普攻，↑ = 技能，↓ = 防御。数字代表本回合行动顺序，例如 1A、2↑。</div><div id="roundEditor"></div><button class="soft" id="addRound" style="margin-top:9px">＋ 新增回合</button>
<h3 class="section-title">作者备注</h3><textarea id="gcNote" style="width:100%" placeholder="例如：第1回合需要赌暴击；攻击低约200也可能通过。"></textarea>
<h3 class="section-title">关键条件</h3><div class="hint">系统会先根据星级、命盘、星石与面板自动判断；作者可在后续版本手动修改关键条件。</div>
<div class="form-actions"><button class="soft" id="saveDraft">保存草稿</button><button class="primary" id="publishNow">发布攻略</button></div>`;
 bindNav(); let picks=[]; let rounds=[]; $('#gcType').onchange=e=>{const on=e.target.value==='限时';$('#endWrap').style.display=on?'grid':'none';$('#limitHint').style.display=on?'block':'none'}; document.querySelectorAll('[data-pick]').forEach(b=>b.onclick=()=>{const id=b.dataset.pick;if(picks.includes(id)){picks=picks.filter(x=>x!==id);b.classList.remove('active')}else if(picks.length<5){picks.push(id);b.classList.add('active')}else return showToast('最多选择 5 个密探');renderPicked(picks)}); $('#addRound').onclick=()=>{if(picks.length!==5)return showToast('请先选择 5 个密探');rounds.push({actions:Array(5).fill(''),note:''});renderRounds(picks,rounds)}; $('#saveDraft').onclick=()=>saveGuide('草稿',picks,rounds); $('#publishNow').onclick=()=>saveGuide('已发布',picks,rounds);
}
function renderPicked(picks){const els=picks.map(id=>profile().agents.find(a=>a.id===id)); $('#pickedEditors').innerHTML=picks.length?`<h3 class="section-title">本篇密探配置</h3><div class="stack">${els.map(a=>`<div class="agent-edit" data-snap="${a.id}"><div class="row between"><b>${esc(a.name)}</b><label style="display:flex;align-items:center;gap:5px"><input type="checkbox" class="sync">同步回我的密探</label></div><div class="form-grid"><label>等级<input data-k="level" type="number" value="${a.level}"></label><label>星级<input data-k="stars" type="number" value="${a.stars}"></label><label>修为<input data-k="rank" type="number" value="${a.rank}"></label><label>攻击<input data-k="atk" type="number" value="${a.atk}"></label><label>生命<input data-k="hp" type="number" value="${a.hp}"></label><label>命盘<input data-k="fate" value="${esc(a.fate)}"></label><label style="grid-column:1/-1">星石<input data-k="stones" value="${esc(a.stones)}"></label></div></div>`).join('')}</div>`:'';}
function renderRounds(picks,rounds){const names=picks.map(id=>profile().agents.find(a=>a.id===id)?.name||'?'); $('#roundEditor').innerHTML=rounds.map((r,ri)=>`<div class="round"><div class="round-head"><b>第 ${ri+1} 回合</b><button class="danger" data-delround="${ri}">删除</button></div>${names.map((n,ai)=>`<div class="action-line" style="margin-top:7px"><span>${esc(n)}</span><select data-order="${ri}-${ai}"><option value="">顺序</option>${[1,2,3,4,5].map(x=>`<option ${r.actions[ai].startsWith(String(x))?'selected':''}>${x}</option>`).join('')}</select><div class="action-buttons">${['A','↑','↓'].map(x=>`<button class="act ${r.actions[ai].endsWith(x)?'on':''}" data-act="${ri}-${ai}-${x}">${x}</button>`).join('')}</div></div>`).join('')}<label style="margin-top:8px">本回合备注<input data-rnote="${ri}" value="${esc(r.note||'')}" placeholder="例如：这里赌暴击"></label></div>`).join(''); document.querySelectorAll('[data-delround]').forEach(b=>b.onclick=()=>{rounds.splice(+b.dataset.delround,1);renderRounds(picks,rounds)}); document.querySelectorAll('[data-order]').forEach(s=>s.onchange=()=>{const [ri,ai]=s.dataset.order.split('-').map(Number);const act=rounds[ri].actions[ai].replace(/^\d/,'');rounds[ri].actions[ai]=(s.value||'')+act;renderRounds(picks,rounds)}); document.querySelectorAll('[data-act]').forEach(b=>b.onclick=()=>{const [ri,ai,act]=b.dataset.act.split('-');const order=(rounds[+ri].actions[+ai].match(/^\d/)||[''])[0];rounds[+ri].actions[+ai]=order+act;renderRounds(picks,rounds)}); document.querySelectorAll('[data-rnote]').forEach(i=>i.oninput=()=>rounds[+i.dataset.rnote].note=i.value);}
function saveGuide(status,picks,rounds){if(!$('#gcTitle').value.trim())return showToast('请填写关卡名称');if(picks.length!==5)return showToast('请选择 5 个密探');const members=[...document.querySelectorAll('[data-snap]')].map(el=>{const base=profile().agents.find(a=>a.id===el.dataset.snap);const obj={name:base.name};el.querySelectorAll('[data-k]').forEach(i=>obj[i.dataset.k]=['level','stars','rank','atk','hp'].includes(i.dataset.k)?+i.value:i.value.trim());if(el.querySelector('.sync').checked)Object.assign(base,obj);return obj});const g={id:'g'+Date.now(),title:$('#gcTitle').value.trim(),author:$('#gcAuthor').value.trim()||account().name,type:$('#gcType').value,status,created:new Date().toISOString().slice(0,10),lastSuccess:'暂无',successCount:0,match:100,matchLabel:'完全匹配',tags:[],team:members.map(m=>m.name),members,rounds,note:$('#gcNote').value.trim(),reports:0,attempted:0,endDate:$('#gcEnd')?.value||''};state.guides.unshift(g);save();showToast(status==='草稿'?'已保存草稿':'攻略已发布');setPage('guides')}

function renderStones(){app.innerHTML=head('星石记录','不使用图片，只保留用于管理和攻略适配的数据。')+`<div class="toolbar"><input class="search" id="stoneSearch" placeholder="搜索星石名称 / 属性"><select id="stoneKind"><option>全部</option><option>主星</option><option>辅星</option></select><button class="primary" id="addStone">＋ 添加星石</button></div><div class="stack">${profile().stones.map(stoneCard).join('')}</div>`;bindNav();$('#addStone').onclick=()=>stoneModal();document.querySelectorAll('[data-stone]').forEach(b=>b.onclick=()=>stoneModal(b.dataset.stone));}
function stoneCard(s){return `<div class="star-card card"><div class="row between"><div><h3 style="margin:0">${esc(s.name)}</h3><div class="meta">${s.kind} · ${s.quality} · Lv.${s.level} · 数量 ${s.count}</div></div><button class="soft" data-stone="${s.id}">编辑</button></div><div class="chips"><span class="chip">加成 ${esc(s.bonus)}</span><span class="chip">当前装备 ${esc(s.equipped||'未装备')}</span></div></div>`}
function stoneModal(id){const p=profile();const s=id?p.stones.find(x=>x.id===id):{id:'s'+Date.now(),name:'',level:1,count:1,kind:'主星',quality:'橙',bonus:'',equipped:''};modalBody.innerHTML=`<div class="modal-head"><h3>${id?'编辑':'添加'}星石</h3><button class="close" id="mclose">×</button></div><div class="form-grid"><label>名称<input id="sName" value="${esc(s.name)}"></label><label>等级<input id="sLevel" type="number" value="${s.level}"></label><label>数量<input id="sCount" type="number" value="${s.count}"></label><label>类型<select id="sKind"><option ${s.kind==='主星'?'selected':''}>主星</option><option ${s.kind==='辅星'?'selected':''}>辅星</option></select></label><label>品质<select id="sQuality">${['橙','紫','蓝','绿'].map(x=>`<option ${s.quality===x?'selected':''}>${x}</option>`).join('')}</select></label><label>属性加成<input id="sBonus" value="${esc(s.bonus)}"></label><label style="grid-column:1/-1">当前装备密探<input id="sEquipped" value="${esc(s.equipped)}"></label></div><div class="form-actions"><button class="soft" id="mCancel">取消</button><button class="primary" id="mSave">保存</button></div>`;modal.showModal();$('#mclose').onclick=$('#mCancel').onclick=()=>modal.close();$('#mSave').onclick=()=>{const obj={...s,name:$('#sName').value.trim(),level:+$('#sLevel').value,count:+$('#sCount').value,kind:$('#sKind').value,quality:$('#sQuality').value,bonus:$('#sBonus').value.trim(),equipped:$('#sEquipped').value.trim()};if(id)p.stones[p.stones.findIndex(x=>x.id===id)]=obj;else p.stones.push(obj);save();modal.close();renderStones();showToast('已保存')};}

function renderRecruit(){app.innerHTML=head('招募记录','先选卡池，再进入卡池维护记录。')+`<div class="stack">${profile().pools.map(poolCard).join('')}</div>`;bindNav();document.querySelectorAll('[data-pool]').forEach(c=>c.onclick=()=>setPage('pool',{poolId:c.dataset.pool}));}
function poolCard(p){return `<div class="pool-card card" data-pool="${p.id}"><div class="pool-banner"></div><div><h3>${esc(p.name)}</h3><p>${esc(p.note||'')}</p></div><div class="chev">›</div></div>`}
function renderPool(id){const p=profile().pools.find(x=>x.id===id);if(!p)return setPage('recruit');const golds=p.golds;const avg=golds.length?(p.totalPulls/golds.length).toFixed(1):'—';const gaps=golds.map(g=>g.gap);const best=gaps.length?Math.min(...gaps):'—',worst=gaps.length?Math.max(...gaps):'—';const counts={};golds.forEach(g=>counts[g.name]=(counts[g.name]||0)+1);const most=Object.entries(counts).sort((a,b)=>b[1]-a[1])[0]?.[0]||'—';const miss={};golds.filter(g=>g.status==='歪').forEach(g=>miss[g.name]=(miss[g.name]||0)+1);const mostMiss=Object.entries(miss).sort((a,b)=>b[1]-a[1])[0]?.[0]||'—';app.innerHTML=head(p.name,p.note)+`
<div class="stats"><div class="stat"><span>总抽数</span><strong>${p.totalPulls}</strong></div><div class="stat"><span>总绝密</span><strong>${golds.length}</strong></div><div class="stat"><span>平均出绝密</span><strong>${avg}</strong></div><div class="stat"><span>最欧一次</span><strong>${best==='—'?best:best+'抽'}</strong></div><div class="stat"><span>最非一次</span><strong>${worst==='—'?worst:worst+'抽'}</strong></div><div class="stat"><span>抽到最多</span><strong>${esc(most)}</strong></div><div class="stat wide"><span>UP池歪出最多</span><strong>${esc(mostMiss)}</strong></div></div>
<div class="row between"><h3 class="section-title" style="margin:0">绝密记录</h3><button class="soft" id="editPool">编辑</button></div>
<div class="gold-grid" style="margin-top:12px">${golds.map((g,i)=>`<div class="gold-item"><div class="gold-face">${avatar(g.name,'lg')}<span class="gold-badge">第 ${i+1} 金</span></div><b>${esc(g.name)}</b><small>${g.gap} 抽</small><span class="gold-tag">${esc(g.status)}</span></div>`).join('')}</div>`;bindNav();$('#editPool').onclick=()=>poolEditModal(p);}
function poolEditModal(p){modalBody.innerHTML=`<div class="modal-head"><h3>编辑 ${esc(p.name)}</h3><button class="close" id="mclose">×</button></div><label>当前总抽数<input id="pTotal" type="number" value="${p.totalPulls}"></label><h4>新增一次出金</h4><div class="form-grid"><label>密探<input id="pName" placeholder="密探名称"></label><label>距上一个金<input id="pGap" type="number" placeholder="例如 37"></label><label>标签<select id="pStatus"><option>UP</option><option>歪</option><option>保底</option><option>双金</option></select></label></div><div class="form-actions"><button class="soft" id="mCancel">取消</button><button class="primary" id="mSave">新增并保存</button></div><h4>已有记录</h4><div class="stack">${p.golds.map((g,i)=>`<div class="row between"><span>第 ${i+1} 金 · ${esc(g.name)} · ${g.gap}抽 · ${esc(g.status)}</span><button class="danger" data-delgold="${i}">删除</button></div>`).join('')}</div>`;modal.showModal();$('#mclose').onclick=$('#mCancel').onclick=()=>modal.close();$('#mSave').onclick=()=>{p.totalPulls=+$('#pTotal').value;if($('#pName').value.trim())p.golds.push({name:$('#pName').value.trim(),gap:+$('#pGap').value||0,status:$('#pStatus').value});save();modal.close();renderPool(p.id);showToast('已保存')};document.querySelectorAll('[data-delgold]').forEach(b=>b.onclick=()=>{p.golds.splice(+b.dataset.delgold,1);save();poolEditModal(p)});}

function renderDex(){app.innerHTML=head('密探图鉴','这一模块尚未定稿，先留空。')+`<div class="card empty"><b>待设计</b><div class="meta" style="margin-top:8px">后续再一起决定图鉴信息和排版。</div></div>`;bindNav()}

$('#accountBtn').onclick=accountModal;$('#moreBtn').onclick=moreModal;
function accountModal(){modalBody.innerHTML=`<div class="modal-head"><h3>切换账号</h3><button class="close" id="mclose">×</button></div><div class="menu-list">${state.accounts.map(a=>`<button data-acc="${a.id}">${a.id===state.current?'✓ ':''}${esc(a.name)}</button>`).join('')}<button id="addAcc">＋ 添加账号</button></div>`;modal.showModal();$('#mclose').onclick=()=>modal.close();document.querySelectorAll('[data-acc]').forEach(b=>b.onclick=()=>{state.current=b.dataset.acc;save();modal.close();render();showToast('已切换账号')});$('#addAcc').onclick=()=>{const name=prompt('新账号名称');if(!name)return;const id='acc'+Date.now();state.accounts.push({id,name});state.profiles[id]={agents:[],stones:[],pools:[]};state.current=id;save();modal.close();render();showToast('已添加账号')};}
function moreModal(){modalBody.innerHTML=`<div class="modal-head"><h3>更多</h3><button class="close" id="mclose">×</button></div><div class="menu-list"><button id="manageAcc">切换 / 添加账号</button><button id="exportData">导出我的数据（JSON）</button></div>`;modal.showModal();$('#mclose').onclick=()=>modal.close();$('#manageAcc').onclick=()=>{modal.close();accountModal()};$('#exportData').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='广陵秘学-数据备份.json';a.click();URL.revokeObjectURL(a.href);showToast('已导出数据')};}
render();
